<a href="https://colab.research.google.com/github/ERIC10000/Introduction-to-Numpy/blob/main/IntroductionToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Numpy

Open Source Libary that forms the Universal Standard of working with Numerical Data(Matrix, Vectors) and forms the underlying foundation for libraries like Pandas and Matplotlib.

### Numpy Arrays
This is the main Data Structure in Numpy and it has the following properties:

1. Can only store a single data type.
2. They can be either one dimension or multi-dimension
3. Their elements can be modified and are fixed-size(cannot change the length)

In [1]:
import numpy as np


In [2]:
# converting a python list to a numpy array
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
print(type(sales))

<class 'list'>


In [3]:
sales_array = np.array(sales)
print(type(sales_array))

<class 'numpy.ndarray'>


In [4]:
# properies
# ndim: number of dimension
# shape: rows and columns
# size: total number of elements
# dtype: Data Type within the array

print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

1
(10,)
10
int64


In [5]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)

print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)


2
(2, 5)
10
int64


## Numpy Array Creation
We use the following function:
1. np.ones()
2. np.zeros()
3. np.arange()
4. np.linspace()
5. np.array.reshape()

In [7]:
# ones: float by default
ones = np.ones(5)
ones.dtype


dtype('float64')

In [9]:
zeros = np.zeros(5, dtype=int)
zeros.dtype

#

dtype('int64')

In [15]:
# arange(start, stop, step)
np.arange(2, 10, 2).reshape(2, 2)

array([[2, 4],
       [6, 8]])

In [14]:
# linspace()
np.linspace(0, 1000, 5)

array([   0.,  250.,  500.,  750., 1000.])

### Indexing and Slicing Numpy Arrays


In [16]:
counties = ["nairobi", "kisumu", "kericho", "nakuru", "kilifi", "kiambu", "laikipia", "nyeri"]
counties_array = np.array(counties).reshape(2,4)
counties_array


array([['nairobi', 'kisumu', 'kericho', 'nakuru'],
       ['kilifi', 'kiambu', 'laikipia', 'nyeri']], dtype='<U8')

In [17]:
kericho_county = counties_array[0, 2]
kericho_county

'kericho'

In [18]:
kilifi_county = counties_array[1, 0]
kilifi_county

'kilifi'

In [21]:
# access for all(:) the record, the first two columns
counties_array.shape
counties_array[:, :2]

array([['nairobi', 'kisumu'],
       ['kilifi', 'kiambu']], dtype='<U8')

In [22]:
# first record, all the columns
counties_array[0, :]

array(['nairobi', 'kisumu', 'kericho', 'nakuru'], dtype='<U8')

### Filtering Numpy Arrays(Conditions)

In [23]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [25]:
condition = sales_array != 0
sales_array[condition]

array([   5,  155,  518, 1827,  616,  317,  325])

In [26]:
# filtering arrays with multiple conditions
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [28]:
condition = (sales_array == 616) | (sales_array < 100)
sales_array[condition]

array([  0,   5,   0,   0, 616])

In [29]:
# Filtering using where(condition, ifblock, elseblock) condition
sales_inventory = np.array([12, 18, 102, 0, 0])
sales_inventory

array([ 12,  18, 102,   0,   0])

In [30]:
# where
np.where(sales_inventory <= 0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [32]:
# products array
products_array = np.array(["egg", "milk", "bread", "rice", "beans"])
products_array

array(['egg', 'milk', 'bread', 'rice', 'beans'], dtype='<U5')

In [33]:
np.where(sales_inventory <= 0, "Out of Stock", products_array)

array(['egg', 'milk', 'bread', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

### Array Aggregation Methods
1. sum()
2. mean()
3. count()
4. median()
5. std()
6. var()
7. max()
8. min()


In [34]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [35]:
total_sales = sales_array.sum()

3763

In [36]:
sales_array.min()

0

In [37]:
sales_array.max()

1827

In [38]:
sales_array.mean()

376.3

In [39]:
sales_array.std()

529.1366647662965

In [40]:
sales_array.var()

279985.61

In [41]:
np.percentile(sales_array, [25, 75])

array([  1.25, 469.75])